import { Button, Title } from "@mantine/core";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [value, setValue] = useState(0);
  return (
    <>
      <Head>
        <title>T3-template</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello!</h1>
      <Title>{value}</Title>
      <Button
        onClick={() => {
          setValue(value + 1);
        }}
      >
        クリックで回数増加
      </Button>
    </>
  );
}
